#!/usr/bin/env python3
"""Run same-source temporal validation on NHANES 2009-2010."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score, brier_score_loss, roc_auc_score

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.evaluation import compute_metrics
from src.reproduction import (
    BALANCED_THRESHOLD,
    CORE_FEATURES,
    DEVELOPMENT_CYCLES,
    PRIMARY_FEATURES,
    RULE_OUT_THRESHOLD,
    TEMPORAL_CYCLE,
    assert_feature_contract,
    bootstrap_ci,
    build_modeling_frame,
    feature_missingness_shift,
    fit_calibrated_ensemble,
    timestamp,
    write_json,
)


def load_frame(input_path: Path) -> pd.DataFrame:
    if input_path.exists() and input_path.name == "nhanes_modeling_frame.parquet":
        frame = pd.read_parquet(input_path)
    elif input_path.exists():
        frame = build_modeling_frame(pd.read_parquet(input_path))
    else:
        fallback = Path("data/processed/nhanes_combined.parquet")
        if not fallback.exists():
            raise FileNotFoundError(f"No processed data found at {input_path} or {fallback}.")
        frame = build_modeling_frame(pd.read_parquet(fallback))
    assert_feature_contract(frame)
    return frame.reset_index(drop=True)


def prevalence_payload(frame: pd.DataFrame) -> dict:
    rows = []
    for cycle, group in frame.groupby("cycle"):
        counts = group["perio_class"].value_counts(normalize=True)
        rows.append(
            {
                "cycle": cycle,
                "n": int(len(group)),
                "prevalence": float(group["has_periodontitis"].mean() * 100),
                "severe": float(counts.get("severe", 0.0) * 100),
                "moderate": float(counts.get("moderate", 0.0) * 100),
                "mild": float(counts.get("mild", 0.0) * 100),
            }
        )
    return {
        "our_estimates": rows,
        "note": "Unweighted analytic-sample prevalence; weighted prevalence is generated by scripts/04_publication_analyses.py.",
        "timestamp": timestamp(),
    }


def decision_curve_summary(y_true: pd.Series, y_prob: np.ndarray) -> dict:
    def net_benefit(threshold: float) -> float:
        pred = (y_prob >= threshold).astype(int)
        y = y_true.to_numpy().astype(int)
        tp = ((pred == 1) & (y == 1)).sum()
        fp = ((pred == 1) & (y == 0)).sum()
        weight = threshold / (1 - threshold)
        return float((tp / len(y)) - (fp / len(y)) * weight)

    return {
        "model": "v1.3_primary",
        "dataset": "NHANES 2009-2010",
        "validation_design": "same-source temporal validation",
        "description": "Decision-curve net benefit at manuscript operating points",
        "data_summary": {
            "model_at_0.35": net_benefit(RULE_OUT_THRESHOLD),
            "model_at_0.65": net_benefit(BALANCED_THRESHOLD),
        },
        "timestamp": timestamp(),
    }


def write_temporal_artifacts(frame: pd.DataFrame, out_dir: Path, predictions_path: Path, bootstrap: int, seed: int) -> dict:
    development = frame[frame["cycle"].isin(DEVELOPMENT_CYCLES)].copy()
    temporal = frame[frame["cycle"] == TEMPORAL_CYCLE].copy()
    if development.empty or temporal.empty:
        raise ValueError("Both development cycles and NHANES 2009-2010 temporal cycle are required.")

    model = fit_calibrated_ensemble(
        development,
        development["has_periodontitis"].astype(int),
        PRIMARY_FEATURES,
        seed=seed,
    )
    y_temporal = temporal["has_periodontitis"].astype(int)
    p_temporal = model.predict_proba(temporal)

    auc_mean, auc_ci = bootstrap_ci(y_temporal, p_temporal, roc_auc_score, n_bootstrap=bootstrap, seed=seed)
    pr_mean, pr_ci = bootstrap_ci(y_temporal, p_temporal, average_precision_score, n_bootstrap=bootstrap, seed=seed + 1)
    brier_mean, brier_ci = bootstrap_ci(y_temporal, p_temporal, brier_score_loss, n_bootstrap=bootstrap, seed=seed + 2)
    rule_out = compute_metrics(y_temporal, p_temporal, threshold=RULE_OUT_THRESHOLD)
    balanced = compute_metrics(y_temporal, p_temporal, threshold=BALANCED_THRESHOLD)

    metrics = {
        "dataset": "NHANES 2009-2010",
        "validation_design": "same-source temporal validation",
        "model": "v1.3_primary_ensemble_calibrated",
        "n_train": int(len(development)),
        "n_test": int(len(temporal)),
        "prevalence_test": float(y_temporal.mean()),
        "metrics": {
            "auc": {"mean": auc_mean, "ci95": auc_ci},
            "prauc": {"mean": pr_mean, "ci95": pr_ci},
            "brier": {"mean": brier_mean, "ci95": brier_ci},
        },
        "operating_points": {
            "rule_out_t_0.35": operating_point(rule_out),
            "balanced_t_0.65": operating_point(balanced),
        },
        "timestamp": timestamp(),
    }
    write_json(out_dir / "external_0910_metrics.json", metrics)
    write_json(
        out_dir / "external_summary.json",
        {
            "dataset": "NHANES 2009-2010",
            "validation_design": "same-source temporal validation",
            "n": int(len(temporal)),
            "prevalence": float(y_temporal.mean()),
            "auc": auc_mean,
            "prauc": pr_mean,
            "brier": brier_mean,
            "rule_out": {"threshold": RULE_OUT_THRESHOLD, **operating_point(rule_out)},
            "balanced": {"threshold": BALANCED_THRESHOLD, **operating_point(balanced)},
            "source": "scripts/run_temporal_validation.py",
            "timestamp": timestamp(),
        },
    )
    write_json(out_dir / "decision_curve_external.json", decision_curve_summary(y_temporal, p_temporal))
    write_json(out_dir / "missingness_shift.json", feature_missingness_shift(development, temporal, CORE_FEATURES))
    write_json(out_dir / "prevalence_check.json", prevalence_payload(frame))

    publication = frame.copy()
    publication["predicted_probability"] = np.nan
    publication.loc[publication["cycle"] == TEMPORAL_CYCLE, "predicted_probability"] = p_temporal
    publication["split"] = np.where(publication["cycle"].isin(DEVELOPMENT_CYCLES), "development", "temporal")
    predictions_path.parent.mkdir(parents=True, exist_ok=True)
    publication.to_parquet(predictions_path)
    return metrics


def operating_point(metrics: dict) -> dict:
    denominator = metrics["tn"] + metrics["fn"]
    npv = float(metrics["tn"] / denominator) if denominator else 0.0
    return {
        "sensitivity": metrics["sensitivity"],
        "specificity": metrics["specificity"],
        "ppv": metrics["precision"],
        "npv": npv,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="data/processed/nhanes_modeling_frame.parquet")
    parser.add_argument("--out-dir", default="results")
    parser.add_argument("--predictions", default="data/processed/publication_predictions.parquet")
    parser.add_argument("--bootstrap", type=int, default=500)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    frame = load_frame(Path(args.input))
    metrics = write_temporal_artifacts(frame, Path(args.out_dir), Path(args.predictions), args.bootstrap, args.seed)
    print(
        "Temporal validation complete: "
        f"AUC={metrics['metrics']['auc']['mean']:.4f}, "
        f"PR-AUC={metrics['metrics']['prauc']['mean']:.4f}, "
        f"Brier={metrics['metrics']['brier']['mean']:.4f}"
    )


if __name__ == "__main__":
    main()
